noise_mean: 0.0
noise_stdev: 0.01
slip_max: 0.1
slip_min: 0.00
max_range: 2.0
basic_sensor_variance: 0.01
scan_angle_min: 0.0
scan_angle_max: 6.28319
scan_angle_increment: 0.1
scan_range_min: 0.12
scan_range_max: 3
